apiVersion: v1
kind: Service
metadata:
  name: database-preparation-service
  labels:
    app: preparation-service
    tier: database-preparation
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5444
      targetPort: 5432
      nodePort: 30038
  selector:
    app: preparation-service
    tier: database-preparation