apiVersion: v1
kind: Service
metadata:
  name: database-reserve-service
  labels:
    app: reserve-service
    tier: database-reserve
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30036
  selector:
    app: reserve-service
    tier: database-reserve
