apiVersion: v1
kind: Service
metadata:
  name: database-payment-service
  labels:
    app: payment-service
    tier: database-payment
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5443
      targetPort: 5432
      nodePort: 30037
  selector:
    app: payment-service
    tier: database-payment