apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-deployment
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
      - name: myapp3
        image: lpmezuraro/spring-payment-service-application:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6102
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom: 
              secretKeyRef:
                name: payment-service-secret
                key: SPRING_DATASOURCE_URL
          - name: SPRING_RABBITMQ_HOST
            valueFrom: 
              secretKeyRef:
                name: services-secrets
                key: SPRING_RABBITMQ_HOST
          - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
            valueFrom: 
              secretKeyRef:
                name: services-secrets
                key: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
          - name: SPRING_ZIPKIN_BASE-URL
            valueFrom: 
              secretKeyRef:
                name: services-secrets
                key: SPRING_ZIPKIN_BASE-URL
          