apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8212
      targetPort: 6102
      nodePort: 30012
  selector:
    app: payment-service