apiVersion: v1
kind: Secret
metadata: 
  name: preparation-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://database_preparation-service:5444/rentacar_preparation_service"
  spring.datasource.url: "jdbc:postgresql://database_preparation-service:30038/rentacar_preparation_service"
  spring.datasource.driver: "org.postgresql.Driver"
  spring.datasource.username: "spring"
  spring.datasource.password: "1234"
  spring.datasource.tomcat.validation-query: "SELECT 1"
  spring.jpa.database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: "true"