apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: reserve-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 5671
      targetPort: 5671
      nodePort: 30509
    - protocol: TCP
      name: amqb
      port: 5672
      targetPort: 5672
      nodePort: 30510
    - protocol: TCP
      name: http2
      port: 15672
      targetPort: 15672
      nodePort: 30511
    - protocol: TCP
      name: other
      port: 25672
      targetPort: 25672
      nodePort: 30512
    - protocol: TCP
      name: other2
      port: 4369
      targetPort: 4369
      nodePort: 30513
  selector:
    app: rabbitmq