apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 6379
      targetPort: 6739
      nodePort: 30739
  selector:
    app: reserve-service