apiVersion: v1
kind: Service
metadata:
  name: reserve-service
  labels:
    app: reserve-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 6101
      targetPort: 6101
      nodePort: 30111
  selector:
    app: reserve-service