apiVersion: v1
kind: Secret
metadata: 
  name: reserve-service-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: 'jdbc:postgresql://database-reserve-service:5442/rentacar_reserve_service'
  spring.datasource.url: "jdbc:postgresql://database-reserve-service:30036/rentacar_reserve_service"
  spring.datasource.driver: "org.postgresql.Driver"
  spring.datasource.username: "spring"
  spring.datasource.password: "1234"
  spring.datasource.tomcat.validation-query: "SELECT 1"
  spring.jpa.database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: "true"